### ISSUE TITLE
Improve Table sorting buttons

### ISSUE THREAD

**Issue by adamkudrna** [react-ui-org/react-ui#21]
Currently, the `Button` component is used for sorting arrows. It would be nice to have them aligned with text in the table, in the same color and without the button-style hover effect.

![image](https://user-images.githubusercontent.com/5614085/74020709-6cf4df80-499a-11ea-8481-44b17a61553d.png)

Maybe also reveal them on hover [like in MUI](https://material-ui.com/components/tables/)?

![image](https://user-images.githubusercontent.com/5614085/74020724-767e4780-499a-11ea-83a0-c420f1f7766d.png)

(Created from #19, relates to #13).

**Comment by mbohal** [comment]
I strongly disagree with showing the arrows on hover. As a user, I wish to see the sort order right away without having to move my pointer over the column header. Also on mobile there would be no way to see the sort order…

**Comment by adamkudrna** [comment]
Alright, alright… Although on mobile we could do it like this:

```css
@media (hover: hover) {
  .sortingButton {
    display: none;
  }

  .sorting:hover .sortingButton {
    display: block;
  }
}
```

This would apply the hover behaviour only on hover enabled devices.
